from .strategies import StrategieCarre, StrategieFonce, StrategieFonceAmeliore, StrategieCarreAmeliore, StrategieTournerDroiteAmeliore, StrategieArcGauche, StrategieArcDroit,StrategieTriangleEquilateral, StrategiePolygone,StrategieTour


#from .strategie import Strategie_avance, Strategie_tourner_droite, Strategie_tourner_gauche, Strategie_carre, Strategie_fonce, Strategie_avance_ameliore, Strategie_tourner_droite_ameliore
