def script():
    Robot mon_robot = new Robot()
    update()
    print("Mon accéleration est : "robot._acceleration)
    print("Ma position en x est : "robot._x)
    print("Ma position en y est : "robot._y)
    print("Ma position en z est : "robot._z)
    print("Ma direction actuelle est : "robot._direction)
    print("Ma direction passée est : "robot._old_direction)

    mon_robot.tourner(50)
    update()
    print("Mon accéleration est : "robot._acceleration)
    print("Ma position en x est : "robot._x)
    print("Ma position en y est : "robot._y)
    print("Ma position en z est : "robot._z)
    print("Ma direction actuelle est : "robot._direction)
    print("Ma direction passée est : "robot._old_direction)

    mon_robot.val_accelerometre()
    update()
    print("Mon accéleration est : "robot._acceleration)
    print("Ma position en x est : "robot._x)
    print("Ma position en y est : "robot._y)
    print("Ma position en z est : "robot._z)
    print("Ma direction actuelle est : "robot._direction)
    print("Ma direction passée est : "robot._old_direction)

    mon_robot.tourner()
    update()
    print("Mon accéleration est : "robot._acceleration)
    print("Ma position en x est : "robot._x)
    print("Ma position en y est : "robot._y)
    print("Ma position en z est : "robot._z)
    print("Ma direction actuelle est : "robot._direction)
    print("Ma direction passée est : "robot._old_direction)

    mon_robot.accelerer()
    update()
    print("Mon accéleration est : "robot._acceleration)
    print("Ma position en x est : "robot._x)
    print("Ma position en y est : "robot._y)
    print("Ma position en z est : "robot._z)
    print("Ma direction actuelle est : "robot._direction)
    print("Ma direction passée est : "robot._old_direction)
    
